---
- name: ensure cloudera-manager-daemons is at the latest version
  yum: pkg=cloudera-manager-daemons state=latest

- name: ensure cloudera-manager-server is at the latest version
  yum: pkg=cloudera-manager-server state=latest

- name: configure cloudera manager databases
  command: "/usr/share/cmf/schema/scm_prepare_database.sh -h {{ scm_db_host }} -P {{ scm_db_port }} {{ scm_db_type }} {{ scm_db_name }} {{ scm_db_user }} {{ scm_db_user_password }} creates={{ scm_done_file }}"

