---
- name: ensure ntp is at the latest version
  yum: pkg=ntp state=latest

- name: ensure ntpd is running
  service: name=ntpd state=running enabled=yes

- name: configure ntp.conf
  template: src=ntp.conf.j2 dest=/etc/ntp.conf owner=root group=root mode=0644
  notify:
    - restart ntpd
