---
- name: copy hive DB setup sql script
  template: src=create_hive_db.sql.j2 dest=/tmp/create_hive_db.sql owner=postgres group=postgres mode=0644

- name: run hive DB setup sql script
  command: "psql -f /tmp/create_hive_db.sql"
  sudo: yes
  sudo_user: postgres

- name: remove hive DB setup sql script
  file: state=absent path=/tmp/create_hive_db.sql

