---
- hosts: tag_Ansible_Group_cdhgw
  roles:
    - selinux
    - firewall
    - kernel
    - transparent_hugepage
    - limits
    - hostname
    - ipv6
    - ntp
    - dig
    - freeipa_client
    - cdh_repos
    - oracle_jdk
    - postgresql_client
